export const MOODS = [
  {
    value: "Rad",
    label: "Rad",
    icon: "🤩",
    bg: "bg-emerald-50 dark:bg-emerald-900/20",
    border: "border-emerald-200 dark:border-emerald-800",
    ring: "ring-emerald-500",
    color: "text-emerald-600 dark:text-emerald-400",
  },
  {
    value: "Good",
    label: "Good",
    icon: "🙂",
    bg: "bg-teal-50 dark:bg-teal-900/20",
    border: "border-teal-200 dark:border-teal-800",
    ring: "ring-teal-500",
    color: "text-teal-600 dark:text-teal-400",
  },
  {
    value: "Meh",
    label: "Meh",
    icon: "😐",
    bg: "bg-slate-50 dark:bg-slate-900/20",
    border: "border-slate-200 dark:border-slate-800",
    ring: "ring-slate-500",
    color: "text-slate-600 dark:text-slate-400",
  },
  {
    value: "Bad",
    label: "Bad",
    icon: "😞",
    bg: "bg-amber-50 dark:bg-amber-900/20",
    border: "border-amber-200 dark:border-amber-800",
    ring: "ring-amber-500",
    color: "text-amber-600 dark:text-amber-400",
  },
  {
    value: "Awful",
    label: "Awful",
    icon: "😭",
    bg: "bg-rose-50 dark:bg-rose-900/20",
    border: "border-rose-200 dark:border-rose-800",
    ring: "ring-rose-500",
    color: "text-rose-600 dark:text-rose-400",
  },
];
